#
# syntax: https://docs.docker.com/compose/yml/
#

version: "3"

services:
    redis:
        ports:
            - 6379:6379

    user:
        env_file: env/production.env

    crawler:
        env_file: env/production.env

    mongo:
        env_file: env/production.env
        
    postgres:
        env_file: env/production.env

    kafka:
        env_file: env/production.env